apiVersion: apps/v1
kind: Deployment
metadata:
  name: kib-auto
  labels:
    name: kib-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kib-auto
  template:
    metadata:
      labels:
        name: kib-auto
    spec:
      containers:
      - name: kib-auto
        image: docker.elastic.co/kibana/kibana:7.11.0
        ports:
        - containerPort: 5601
          name: http
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://158.98.6.18:31996"
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: elasticsearch-credentials
                key: username
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-credentials
                key: password        
---
apiVersion: v1
kind: Service
metadata:
  name: kib-auto
  labels:
    name: kib-auto
spec:
  type: ClusterIP
  externalIPs:
    - 158.98.6.18
  selector:
    name: kib-auto
  ports:
    - port: 31997
      targetPort: 5601
      protocol: TCP
      
