apiVersion: apps/v1
kind: Deployment
metadata:
  name: kib-auto
  labels:
    name: kib-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kib-auto
  template:
    metadata:
      labels:
        name: kib-auto
    spec:
      containers:
      - name: kib-auto
        image: kibana:7.8.0
        ports:
        - containerPort: 5601
          name: http
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://127.0.0.1:31996"
---
apiVersion: v1
kind: Service
metadata:
  name: kib-auto
  labels:
    name: kib-auto
spec:
  type: NodePort
  selector:
    name: kib-auto
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 31997
      protocol: TCP
      
