apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-auto
  labels:
    name: log-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: log-auto
  template:
    metadata:
      labels:
        name: log-auto
    spec:
      containers:
      - name: log-auto
        image: logstash:7.8.0
        ports:
        - containerPort: 5044
          name: filebeat
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://127.0.0.1:31996"
        volumeMounts:
            - name: log-auto-pipeline
              mountPath: /usr/share/logstash/pipeline/
        command:
            - logstash      
      volumes:
        - name: log-auto-pipeline
          configMap:
            name: log-auto-pipeline
            items:
              - key: logstash.conf
                path: logstash.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-auto-pipeline
data:
  logstash.conf: '{{ .Files.Get "logstash.conf" | indent 4 }}'
---
apiVersion: v1
kind: Service
metadata:
  name: log-auto
  labels:
    name: log-auto
spec:
  type: NodePort
  selector:
    name: log-auto
  ports:
  - port: 5044
    targetPort: 5044
    nodePort: 31998
    protocol: TCP