apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-auto
  labels:
    name: log-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: log-auto
  template:
    metadata:
      labels:
        name: log-auto
    spec:
      containers:
      - name: log-auto
        image: docker.elastic.co/logstash/logstash:7.11.0
        ports:
        - containerPort: 5044
          name: filebeat
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://158.98.6.18:31996"
        volumeMounts:
            - name: log-auto-pipeline
              mountPath: /usr/share/logstash/pipeline/
        command:
            - logstash      
      volumes:
        - name: log-auto-pipeline
          configMap:
            name: log-auto-pipeline
            items:
              - key: logstash.conf
                path: logstash.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-auto-pipeline
data:
  logstash.conf: '{{ .Files.Get "logstash.conf" | indent 4 }}'
---
apiVersion: v1
kind: Service
metadata:
  name: log-auto
  labels:
    name: log-auto
spec:
  type: ClusterIP
  externalIPs:
    - 158.98.6.18
  selector:
    name: log-auto
  ports:
    - port: 31998
      targetPort: 5044
      protocol: TCP